<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => '',
    'homepage' => 'Home',
  ),
);


/* Auto generated by Themes Administration on : 2015.02.09 15:20:32 */
