<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'article_page' => 'Article_page',
  ),
  'page' => 
  array (
    'page' => '',
    'home_page' => 'Homapage',
  ),
);


/* Auto generated by Themes Administration on : 2015.02.11 23:20:03 */
