<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => '',
    'home_page' => 'Homapage',
  ),
);


/* Auto generated by Themes Administration on : 2015.02.09 18:09:44 */
